language: ruby
rvm:
  - 2.3.1

# Use caching
cache:
  bundler: true

# Use PostgreSQL as database
services:
  - postgresql

before_script:
  - psql -c 'create database upshift_network_test;' -U postgres

script:
  - bundle exec rspec spec/

bundler_args: --without development production

# whitelist
branches:
  only:
    - master
    - development

# spoof some environment variables so that tests can pass
env:
  global:
    - MAILJET_API_KEY=spoof
    - MAILJET_SECRET_KEY=spoof
    - USER_REGISTRATION_EMAIL_TEMPLATE_ID=spoof
